package applyprogress

import "strings"

const VerifyReportReasonRegenerateWithSDDVerify = "regenerate_with_sdd_verify"

// VerifyReportError identifies a verification report that must be regenerated by
// sdd-verify before archive can proceed.
type VerifyReportError struct {
	Code string
}

func (e *VerifyReportError) Error() string {
	return "verify report: " + e.Code
}

// VerifyReportReadiness is the canonical active verification report decision.
// Code is set only when the report is not a canonical active report and must be
// regenerated by sdd-verify. Canonical reports with failing findings remain
// non-ready without requesting regeneration.
type VerifyReportReadiness struct {
	Ready bool
	Code  string
}

// InspectVerifyReport evaluates only the canonical active verification fields.
// Narrative and historical sections are deliberately ignored: archive readiness
// is determined mechanically by the current Verdict, Critical Findings, and
// Blockers sections.
func InspectVerifyReport(content string) VerifyReportReadiness {
	sections, canonical := canonicalVerifySections(content)
	if !canonical {
		return VerifyReportReadiness{Code: VerifyReportReasonRegenerateWithSDDVerify}
	}

	verdict := normalizeMarkdownValue(sections["Verdict"])
	criticals := normalizeMarkdownValue(sections["Critical Findings"])
	blockers := normalizeMarkdownValue(sections["Blockers"])
	if !isCanonicalVerdict(verdict) || criticals == "" || blockers == "" {
		return VerifyReportReadiness{Code: VerifyReportReasonRegenerateWithSDDVerify}
	}

	return VerifyReportReadiness{
		Ready: (verdict == "pass — archive ready." || verdict == "pass with warnings — archive ready.") &&
			criticals == "0" && blockers == "none",
	}
}

// VerifyReportArchiveReady accepts only a canonical active verification report
// whose current fields explicitly permit archive.
func VerifyReportArchiveReady(content string) bool {
	return InspectVerifyReport(content).Ready
}

func isCanonicalVerdict(verdict string) bool {
	switch verdict {
	case "pass — archive ready.", "pass with warnings — archive ready.", "fail":
		return true
	default:
		return false
	}
}

// canonicalVerifySections accepts each required heading exactly once and retains
// only its non-empty body. Other sections are narrative and have no bearing on
// active archive readiness.
func canonicalVerifySections(content string) (map[string]string, bool) {
	required := map[string]string{
		"verdict":           "Verdict",
		"critical findings": "Critical Findings",
		"blockers":          "Blockers",
	}
	sections := make(map[string]string, len(required))
	counts := make(map[string]int, len(required))
	canonical := true
	current := ""
	var body []string
	flush := func() {
		if current != "" {
			sections[current] = strings.Join(body, "\n")
		}
	}

	for _, raw := range strings.Split(content, "\n") {
		line := strings.TrimSpace(raw)
		if strings.HasPrefix(line, "## ") {
			flush()
			current = ""
			body = nil
			name := line[3:]
			if expected, ok := required[strings.ToLower(name)]; ok {
				canonical = canonical && name == expected
				current = expected
				counts[current]++
			}
			continue
		}
		if current != "" && line != "" {
			body = append(body, line)
		}
	}
	flush()

	for _, heading := range required {
		if counts[heading] != 1 || sections[heading] == "" {
			canonical = false
		}
	}
	return sections, canonical
}

func normalizeMarkdownValue(value string) string {
	value = strings.TrimSpace(value)
	for {
		switch {
		case strings.HasPrefix(value, "**") && strings.HasSuffix(value, "**") && len(value) >= 4:
			value = strings.TrimSpace(value[2 : len(value)-2])
		case strings.HasPrefix(value, "_") && strings.HasSuffix(value, "_") && len(value) >= 2:
			value = strings.TrimSpace(value[1 : len(value)-1])
		default:
			return strings.ToLower(value)
		}
	}
}
