package agent

import (
	"bytes"
	"fmt"
	"os"
	"text/template"
)

const startScriptTemplate = `#!/bin/bash
# hive-daemon-start.sh — generated by jarvis-cli. Do not edit manually.
# Re-run 'jarvis login' to update credentials.
export HIVE_API_URL="{{.APIURL}}"
export HIVE_API_EMAIL="{{.Email}}"
export HIVE_API_PASSWORD="{{.Password}}"
exec {{.DaemonPath}}
`

// StartScriptData holds the variables for the hive-daemon start script template.
type StartScriptData struct {
	APIURL     string
	Email      string
	Password   string
	DaemonPath string
}

// GenerateStartScript renders the hive-daemon-start.sh content from template.
func GenerateStartScript(data StartScriptData) (string, error) {
	tmpl, err := template.New("start").Parse(startScriptTemplate)
	if err != nil {
		return "", fmt.Errorf("parse start script template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("render start script: %w", err)
	}

	return buf.String(), nil
}

// WriteStartScript writes the start script to path.
// If the file already exists, it is backed up to path+".bak" before overwriting.
func WriteStartScript(path, content string) error {
	// Back up existing file if present
	if _, err := os.Stat(path); err == nil {
		backupPath := path + ".bak"
		existing, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read existing start script for backup: %w", err)
		}
		if err := os.WriteFile(backupPath, existing, 0755); err != nil {
			return fmt.Errorf("write backup to %s: %w", backupPath, err)
		}
	}

	// Write new script (executable)
	if err := writeFileAtomic(path, []byte(content), 0755); err != nil {
		return fmt.Errorf("write start script: %w", err)
	}

	return nil
}
